config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions:      'admin/admins/sessions',
    passwords:     'admin/admins/passwords'
  }

 namespace :admin do

   get "/" => "homes#top"
   resources :customers,only: [:index,:show,:edit,:update]
   resources :genres,only: [:index,:create,:edit,:update]
   resources :tags,only: [:index,:create,:edit,:update]
   resources :works, only: [:index,:show,:destroy]
 end

 devise_for :customers, controllers: {
   sessions:      'public/customers/sessions',
   passwords:     'public/customers/passwords',
   registrations: 'public/customers/registrations'
 }

 root to: "public/homes#top"
 get "search" => "searches#search"
 get "/about" => "public/homes#about"
 get "/follow" => "public/homes#follow"

  scope module: :public do
   get "/customers/my_page" => 'customers#mypage'
   get '/customers/history' => 'customers#history'
   get '/customers/confirm' => 'customers#confirm'
   get '/customers/like' => 'customers#like'
   patch '/customers/withdraw' => 'customers#withdraw'
   resources :customers,only: [:show,:edit,:update]do
    get :favorites, on: :collection
    resources :relationships, only: [:create, :destroy]
   end
   get '/works/ranking/:ranking_name' => 'works#ranking', as: 'works_ranking'
   resources :works, only: [:index,:show,:create,:new,:edit,:update,:destroy]do
    resources :reviews,only: [:index,:show,:new,:create,:destroy]do
     resources :comments,only: [:create,:destroy]
   end
    resources :favorites, only: [:create, :destroy]
   end
   resources :rooms,only: [:index]

   get 'chat/:id' => 'chats#show', as: 'chat'
   delete 'chat/:id' => 'chats#destroy'
   resources :chats, only: [:create]

 end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :customer
  belongs_to :room

  validates :message, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :customer
    belongs_to :review
    belongs_to :parent,  class_name: "Comment", optional: true
    has_many   :replies, class_name: "Comment", foreign_key: :parent_id, dependent: :destroy
    validates :comment, presence: true, length: { in: 1..1000 }
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  enum gender:{
    man:     0, #男
    woman:   1, #女
  }

  attachment :image

  validates :nicname, presence: true
  validates :introduction, presence: true
  validates :email, presence: true


  def self.looks(search, word)
    if search == "perfect_match"
      @customer = Customer.where("nicname LIKE?", "#{word}")
    elsif search == "forward_match"
      @customer = Customer.where("nicname LIKE?","#{word}%")
    elsif search == "backward_match"
      @customer = Customer.where("nicname LIKE?","%#{word}")
    elsif search == "partial_match"
      @customer = Customer.where("nicname LIKE?","%#{word}%")
    else
      @customer = Customer.all
    end
  end

  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following_customer, through: :follower, source: :followed
  has_many :follower_customer, through: :followed, source: :follower


  def follow(cusromer_id)
    follower.create(followed_id: cusromer_id)
  end


  def unfollow(customer_id)
    follower.find_by(followed_id: customer_id).destroy
  end


  def following?(customer)
    following_customer.include?(customer)
  end

  has_many :reviews, dependent: :destroy
  has_many :matchings, dependent: :destroy
  has_many :chats, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :works, dependent: :destroy
  has_many :comments, dependent: :destroy

end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :customer
    belongs_to :work
    
    validates_uniqueness_of :work_id, scope: :customer_id 
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :works, dependent: :destroy
    
    validates :name, presence: true
end

app/models/matching.rb
class Matching < ApplicationRecord
    belongs_to :customer
    belongs_to :room
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "Customer"
  belongs_to :followed, class_name: "Customer"
end

app/models/review.rb
class Review < ApplicationRecord
     belongs_to :customer
     belongs_to :work
     has_many :comments, dependent: :destroy
     
     validates :rate, numericality: {
          less_than_or_equal_to: 5,
          greater_than_or_equal_to: 1
     }, presence: true
     
     validates :thoughts, presence: true
     
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :matchings
  has_many :chats
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tagmaps, dependent: :destroy
  has_many :blogs, through: :tagmaps

  validates :name, presence: true
end

app/models/tagmap.rb
class Tagmap < ApplicationRecord
  belongs_to :work
  belongs_to :tag
end

app/models/work.rb
class Work < ApplicationRecord
    has_many :tagmaps, dependent: :destroy
    has_many :tags, through: :tagmaps
    belongs_to :genre
    belongs_to :customer
    has_many :reviews, dependent: :destroy
    has_many :favorites, dependent: :destroy

    attachment :image

    accepts_nested_attributes_for :tags, allow_destroy: true

    validates :name, presence: true

    def self.looks(search, word)
        if search == "perfect_match"
          @work = Work.where("name LIKE?", "#{word}")
        elsif search == "forward_match"
          @work = Work.where("name LIKE?","#{word}%")
        elsif search == "backward_match"
          @work = Work.where("name LIKE?","%#{word}")
        elsif search == "partial_match"
          @work = Work.where("name LIKE?","%#{word}%")
        else
          @work = Work.all
        end
    end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.all
    @customers = Customer.page(params[:page]).per(10)
  end


  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])

  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customer_path(@customer.id)
    else
     render :edit
    end
  end

  def customer_params
    params.require(:customer).permit(:nicname,:email,:gender,:prefectures,:image,:introduction,:is_active)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?




  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nicname,:email,:image,:prefectures,:gender,:introduction])
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
    before_action :authenticate_customer!

  def search
    @range = params[:range]
    if @range == "作品"
        @works = Work.looks(params[:search], params[:word])
    else
        @customers = Customer.looks(params[:search], params[:word])
    end
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/helpers/admin/works_helper.rb
module Admin::WorksHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1><%= @customer.nicname %>さんの会員情報編集</h1>
      <%= form_with model: @customer,url: admin_customer_path, local:true do |f| %>
        <div class="form-group">
          <label for="status">会員ステータス</label>
          <%= f.radio_button :is_active, :true %>
          <%= f.label :is_active, "有効", {value: :true, style: "display: inline-block;"} %>
          <%= f.radio_button :is_active, :false %>
          <%= f.label :is_active, "退会", {value: :false, style: "display: inline-block;"} %>
        </div>
        <div class="form-group">
          <%= f.submit "変更を保存", class:"btn btn-success" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>会員一覧</h1>
      <table class = "table">
        <thead>
          <tr>
            <th>会員ID</th>
            <th>ニックネーム</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @customers.each do |customer| %>
            <tr class="customer-box">
              <td><%= customer.id %></td>
              <td><%= link_to customer.nicname, admin_customer_path(customer.id)%></td>
              <td><%= customer.email %></td>
              <% if customer.is_active == true %>
                <td><%= "有効" %></td>
              <% else %>
                <td><%= "退会" %></td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= paginate @customers, theme: 'twitter-bootstrap-4' %>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class = "container">
    <h2><%= @customer.nicname %>さんの会員詳細</h2>
    <table class="table table-hover table-inverse">
        <tbody>
            <tr class="customer-box">
                <td>会員</td>
                <td><%= @customer.id %></td>
            </tr>
            
            <tr>
                <td>ニックネーム</td>
                <td>
                  <%= @customer.nicname %><br>
                  <%= attachment_image_tag @customer, :image, size: '100x100', format: 'jpeg', class:"attachment image fallback" %>
                </td>
            </tr>
            
            <tr>
                <td>性別</td>
                <td><%= @customer.gender_i18n %></td>
            </tr>
            
            <tr>
                <td>都道府県</td>
                <td><%= @customer.prefectures %></td>
            </tr>
            
            <tr>
                <td>メールアドレス</td>
                <td><%= @customer.email %></td>
            </tr>
            
            <tr>
                <td>自己紹介</td>
                <td><%= @customer.introduction %></td>
            </tr>
            <tr>
                <td>会員ステータス</td>
                <% if @customer.is_active == true %>
                    <td><%= "有効" %></td>
                <% else %>
                   <td><%= "退会" %></td>
                <% end %>
            </tr>
        </tbody>
    </table>
    <%= link_to "編集する", edit_admin_customer_path, class:"btn btn-sm btn-success" %>
 </div>