config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions:      'admin/admins/sessions',
    passwords:     'admin/admins/passwords'
  }

 namespace :admin do

   get "/" => "homes#top"
   resources :customers,only: [:index,:show,:edit,:update]
   resources :genres,only: [:index,:create,:edit,:update]
   resources :tags,only: [:index,:create,:edit,:update]
   resources :works, only: [:index,:show,:destroy]
 end

 devise_for :customers, controllers: {
   sessions:      'public/customers/sessions',
   passwords:     'public/customers/passwords',
   registrations: 'public/customers/registrations'
 }

 root to: "public/homes#top"
 get "search" => "searches#search"
 get "/about" => "public/homes#about"
 get "/follow" => "public/homes#follow"

  scope module: :public do
   get "/customers/my_page" => 'customers#mypage'
   get '/customers/history' => 'customers#history'
   get '/customers/confirm' => 'customers#confirm'
   get '/customers/like' => 'customers#like'
   patch '/customers/withdraw' => 'customers#withdraw'
   resources :customers,only: [:show,:edit,:update]do
    get :favorites, on: :collection
    resources :relationships, only: [:create, :destroy]
   end
   get '/works/ranking/:ranking_name' => 'works#ranking', as: 'works_ranking'
   resources :works, only: [:index,:show,:create,:new,:edit,:update,:destroy]do
    resources :reviews,only: [:index,:show,:new,:create,:destroy]do
     resources :comments,only: [:create,:destroy]
   end
    resources :favorites, only: [:create, :destroy]
   end
   resources :rooms,only: [:index]

   get 'chat/:id' => 'chats#show', as: 'chat'
   delete 'chat/:id' => 'chats#destroy'
   resources :chats, only: [:create]

 end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :customer
  belongs_to :room

  validates :message, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :customer
    belongs_to :review
    belongs_to :parent,  class_name: "Comment", optional: true
    has_many   :replies, class_name: "Comment", foreign_key: :parent_id, dependent: :destroy
    validates :comment, presence: true, length: { in: 1..1000 }
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  enum gender:{
    man:     0, #男
    woman:   1, #女
  }

  attachment :image

  validates :nicname, presence: true
  validates :introduction, presence: true
  validates :email, presence: true


  def self.looks(search, word)
    if search == "perfect_match"
      @customer = Customer.where("nicname LIKE?", "#{word}")
    elsif search == "forward_match"
      @customer = Customer.where("nicname LIKE?","#{word}%")
    elsif search == "backward_match"
      @customer = Customer.where("nicname LIKE?","%#{word}")
    elsif search == "partial_match"
      @customer = Customer.where("nicname LIKE?","%#{word}%")
    else
      @customer = Customer.all
    end
  end

  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following_customer, through: :follower, source: :followed
  has_many :follower_customer, through: :followed, source: :follower


  def follow(cusromer_id)
    follower.create(followed_id: cusromer_id)
  end


  def unfollow(customer_id)
    follower.find_by(followed_id: customer_id).destroy
  end


  def following?(customer)
    following_customer.include?(customer)
  end

  has_many :reviews, dependent: :destroy
  has_many :matchings, dependent: :destroy
  has_many :chats, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :works, dependent: :destroy
  has_many :comments, dependent: :destroy

end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :customer
    belongs_to :work
    
    validates_uniqueness_of :work_id, scope: :customer_id 
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :works, dependent: :destroy
    
    validates :name, presence: true
end

app/models/matching.rb
class Matching < ApplicationRecord
    belongs_to :customer
    belongs_to :room
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "Customer"
  belongs_to :followed, class_name: "Customer"
end

app/models/review.rb
class Review < ApplicationRecord
     belongs_to :customer
     belongs_to :work
     has_many :comments, dependent: :destroy
     
     validates :rate, numericality: {
          less_than_or_equal_to: 5,
          greater_than_or_equal_to: 1
     }, presence: true
     
     validates :thoughts, presence: true
     
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :matchings
  has_many :chats
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tagmaps, dependent: :destroy
  has_many :blogs, through: :tagmaps

  validates :name, presence: true
end

app/models/tagmap.rb
class Tagmap < ApplicationRecord
  belongs_to :work
  belongs_to :tag
end

app/models/work.rb
class Work < ApplicationRecord
    has_many :tagmaps, dependent: :destroy
    has_many :tags, through: :tagmaps
    belongs_to :genre
    belongs_to :customer
    has_many :reviews, dependent: :destroy
    has_many :favorites, dependent: :destroy

    attachment :image

    accepts_nested_attributes_for :tags, allow_destroy: true

    validates :name, presence: true

    def self.looks(search, word)
        if search == "perfect_match"
          @work = Work.where("name LIKE?", "#{word}")
        elsif search == "forward_match"
          @work = Work.where("name LIKE?","#{word}%")
        elsif search == "backward_match"
          @work = Work.where("name LIKE?","%#{word}")
        elsif search == "partial_match"
          @work = Work.where("name LIKE?","%#{word}%")
        else
          @work = Work.all
        end
    end

end

app/controllers/admin/works_controller.rb
class Admin::WorksController < ApplicationController
  def index
      @genre_id = params[:genre_id]
      if params[:genre_id].present?
          @works = Work.where(genre_id: params[:genre_id]).page(params[:page]).per(20)
          if params[:tag_id].present?
              @works = @works.joins(:tags).where(tags: {id: params[:tag_id]}).page(params[:page]).per(20)
          end
      else
          @works = Work.all
          if params[:tag_id].present?
              @works = @works.joins(:tags).where(tags: {id: params[:tag_id]}).page(params[:page]).per(20)
          else
              @works = Work.all.page(params[:page]).per(20)
          end
      end

      @tags = Tag.all
  end

  def show
      @work = Work.find(params[:id])
  end

  def new
      @work = Work.new
      @genres = Genre.all
  end



  def destroy
      @work = Work.find(params[:id])
      @work.destroy
      redirect_to works_path
  end

  def work_params
      params.require(:work).permit(:name, :image, :synopsis, :release_date, :genre_id, tag_ids: [])
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?




  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nicname,:email,:image,:prefectures,:gender,:introduction])
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
    before_action :authenticate_customer!

  def search
    @range = params[:range]
    if @range == "作品"
        @works = Work.looks(params[:search], params[:word])
    else
        @customers = Customer.looks(params[:search], params[:word])
    end
  end
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/helpers/admin/works_helper.rb
module Admin::WorksHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/admin/works/index.html.erb
<div class="container px-5 px-sm-0">
    <div class="row">
        <div class="col-md-3">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>タグ</th>
                    </tr>
                </thead>
                <tbody>
                    <% @tags.each do |tag| %>
                    <tr class="tag-box">
                        <% if @genre_id.present? %>
                          <td><%= link_to tag.name, admin_works_path(genre_id: @genre_id, tag_id: tag.id) %></td>
                        <% else %>
                          <td><%= link_to tag.name, admin_works_path(tag_id: tag.id) %></td>
                        <% end %>
                    </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
        
        <div class="col-md-8 offset-md-1">
            <h1>作品一覧</h1>
            <div class = "row">
                <% @works.each do |work| %>
                <div class = "work col-md-3" >
                    <%= link_to admin_work_path(work.id) do%>
                      <%= attachment_image_tag work, :image, size: '100x100', format: 'jpeg', class:"attachment image fallback" %>
                    <% end %><br>
                      <%= link_to work.name, admin_work_path(work.id)%><br>
                      <%= work.release_date %>
                </div>
                <% end %>
            </div>
           <%= paginate @works, theme: 'twitter-bootstrap-4' %>
        </div>
    </div>
</div>

app/views/admin/works/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-5">
            <%= attachment_image_tag @work, :image, size: '300x300', format: 'jpeg', class:"attachment image fallback" %>
        </div>
        <div class="col-md-">
            <h2>作品詳細</h2>
            <table class="table table-hover table-inverse">
                <tbody>
                    <tr class="work-box">
                        <td>作品名</td>
                        <td><%= @work.name %></td>
                    </tr>
                    
                    <tr class="work-box">
                        <td>公開日</td>
                        <td><%= @work.release_date %></td>
                    </tr>
                     
                    <tr class="work-box">
                        <td>あらすじ</td>
                        <td><%= @work.synopsis %></td>
                    </tr>
                     
                    <tr class="work-box">
                        <td>ジャンル</td>
                        <td><%= @work.genre.name %></td>
                    </tr>
                     
                    <tr class="work-box">
                      <td>タグ</td>
                      <% @work.tags.each do |list| %>
                         <td><%= list.name %></td>
                      <% end %>
                    </tr>
                </tbody>
            </table>
            <%= link_to "削除する", admin_work_path(@work.id), method: :delete,data: {confirm: "削除しますか？"}, class:"btn btn-sm btn-danger" %>
        </div>
    </div>
</div>