config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions:      'admin/admins/sessions',
    passwords:     'admin/admins/passwords'
  }

 namespace :admin do

   get "/" => "homes#top"
   resources :customers,only: [:index,:show,:edit,:update]
   resources :genres,only: [:index,:create,:edit,:update]
   resources :tags,only: [:index,:create,:edit,:update]
   resources :works, only: [:index,:show,:destroy]
 end

 devise_for :customers, controllers: {
   sessions:      'public/customers/sessions',
   passwords:     'public/customers/passwords',
   registrations: 'public/customers/registrations'
 }

 root to: "public/homes#top"
 get "search" => "searches#search"
 get "/about" => "public/homes#about"
 get "/follow" => "public/homes#follow"

  scope module: :public do
   get "/customers/my_page" => 'customers#mypage'
   get '/customers/history' => 'customers#history'
   get '/customers/confirm' => 'customers#confirm'
   get '/customers/like' => 'customers#like'
   patch '/customers/withdraw' => 'customers#withdraw'
   resources :customers,only: [:show,:edit,:update]do
    get :favorites, on: :collection
    resources :relationships, only: [:create, :destroy]
   end
   get '/works/ranking/:ranking_name' => 'works#ranking', as: 'works_ranking'
   resources :works, only: [:index,:show,:create,:new,:edit,:update,:destroy]do
    resources :reviews,only: [:index,:show,:new,:create,:destroy]do
     resources :comments,only: [:create,:destroy]
   end
    resources :favorites, only: [:create, :destroy]
   end
   resources :rooms,only: [:index]

   get 'chat/:id' => 'chats#show', as: 'chat'
   delete 'chat/:id' => 'chats#destroy'
   resources :chats, only: [:create]

 end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :customer
  belongs_to :room

  validates :message, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :customer
    belongs_to :review
    belongs_to :parent,  class_name: "Comment", optional: true
    has_many   :replies, class_name: "Comment", foreign_key: :parent_id, dependent: :destroy
    validates :comment, presence: true, length: { in: 1..1000 }
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  enum gender:{
    man:     0, #男
    woman:   1, #女
  }

  attachment :image

  validates :nicname, presence: true
  validates :introduction, presence: true
  validates :email, presence: true


  def self.looks(search, word)
    if search == "perfect_match"
      @customer = Customer.where("nicname LIKE?", "#{word}")
    elsif search == "forward_match"
      @customer = Customer.where("nicname LIKE?","#{word}%")
    elsif search == "backward_match"
      @customer = Customer.where("nicname LIKE?","%#{word}")
    elsif search == "partial_match"
      @customer = Customer.where("nicname LIKE?","%#{word}%")
    else
      @customer = Customer.all
    end
  end

  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following_customer, through: :follower, source: :followed
  has_many :follower_customer, through: :followed, source: :follower


  def follow(cusromer_id)
    follower.create(followed_id: cusromer_id)
  end


  def unfollow(customer_id)
    follower.find_by(followed_id: customer_id).destroy
  end


  def following?(customer)
    following_customer.include?(customer)
  end

  has_many :reviews, dependent: :destroy
  has_many :matchings, dependent: :destroy
  has_many :chats, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :works, dependent: :destroy
  has_many :comments, dependent: :destroy

end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :customer
    belongs_to :work
    
    validates_uniqueness_of :work_id, scope: :customer_id 
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :works, dependent: :destroy
    
    validates :name, presence: true
end

app/models/matching.rb
class Matching < ApplicationRecord
    belongs_to :customer
    belongs_to :room
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "Customer"
  belongs_to :followed, class_name: "Customer"
end

app/models/review.rb
class Review < ApplicationRecord
     belongs_to :customer
     belongs_to :work
     has_many :comments, dependent: :destroy
     
     validates :rate, numericality: {
          less_than_or_equal_to: 5,
          greater_than_or_equal_to: 1
     }, presence: true
     
     validates :thoughts, presence: true
     
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :matchings
  has_many :chats
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tagmaps, dependent: :destroy
  has_many :blogs, through: :tagmaps

  validates :name, presence: true
end

app/models/tagmap.rb
class Tagmap < ApplicationRecord
  belongs_to :work
  belongs_to :tag
end

app/models/work.rb
class Work < ApplicationRecord
    has_many :tagmaps, dependent: :destroy
    has_many :tags, through: :tagmaps
    belongs_to :genre
    belongs_to :customer
    has_many :reviews, dependent: :destroy
    has_many :favorites, dependent: :destroy

    attachment :image

    accepts_nested_attributes_for :tags, allow_destroy: true

    validates :name, presence: true

    def self.looks(search, word)
        if search == "perfect_match"
          @work = Work.where("name LIKE?", "#{word}")
        elsif search == "forward_match"
          @work = Work.where("name LIKE?","#{word}%")
        elsif search == "backward_match"
          @work = Work.where("name LIKE?","%#{word}")
        elsif search == "partial_match"
          @work = Work.where("name LIKE?","%#{word}%")
        else
          @work = Work.all
        end
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?




  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nicname,:email,:image,:prefectures,:gender,:introduction])
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
    before_action :authenticate_customer!

  def search
    @range = params[:range]
    if @range == "作品"
        @works = Work.looks(params[:search], params[:word])
    else
        @customers = Customer.looks(params[:search], params[:word])
    end
  end
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/helpers/admin/works_helper.rb
module Admin::WorksHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_searches.html.erb
<% if customer_signed_in? %>
  <div class="search_form">
    <%= form_with url: search_path, local: true, method: :get do |f| %>
      <%= f.text_field :word %>
      <%= f.select :range, options_for_select([['作品'], ['会員']]) %>
      <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"],  ["後方一致","backword_match"], ["部分一致","partial_match"]]) %>
      <%= f.submit "検索", class: "btn btn-primary" %>
    <% end %>
  </div>
<% end %>

app/views/searches/search.html.erb
<div class="container">
    <div class="row" id = "search">
        <div class="col-sm-12 col-md-8 ">
            <h1>検索結果</h1>
            <div class = "row">
                <% if @range == "作品" %>
                    <% @works.each do |work| %>
                        <div class = "work col-md-3" >
                            <%= link_to work_path(work.id) do %>
                              <%= attachment_image_tag work, :image, size: '150x150', format: 'jpeg', class:"attachment image fallback" %>
                            <% end %><br>
                            <%= link_to work.name, work_path(work.id) %><br>
                            <%= work.genre.name %>
                        </div>
                    <% end %>
                <% else %>
                    <% @customers.each do |customer| %>
                        <div class = "customer col-md-3" >
                            <%= link_to customer_path(customer.id) do %>
                                <%= attachment_image_tag customer, :image, size: '150x150', format: 'jpeg', class:"attachment image fallback" %>
                            <% end %><br>
                            <%= link_to customer.nicname, customer_path(customer.id) %>
                        </div>
                    <% end %>
                <% end %>
                
            </div>
        </div>
    </div>
</div> 




  
  
     