config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions:      'admin/admins/sessions',
    passwords:     'admin/admins/passwords'
  }

 namespace :admin do

   get "/" => "homes#top"
   resources :customers,only: [:index,:show,:edit,:update]
   resources :genres,only: [:index,:create,:edit,:update]
   resources :tags,only: [:index,:create,:edit,:update]
   resources :works, only: [:index,:show,:destroy]
 end

 devise_for :customers, controllers: {
   sessions:      'public/customers/sessions',
   passwords:     'public/customers/passwords',
   registrations: 'public/customers/registrations'
 }

 root to: "public/homes#top"
 get "search" => "searches#search"
 get "/about" => "public/homes#about"
 get "/follow" => "public/homes#follow"

  scope module: :public do
   get "/customers/my_page" => 'customers#mypage'
   get '/customers/history' => 'customers#history'
   get '/customers/confirm' => 'customers#confirm'
   get '/customers/like' => 'customers#like'
   patch '/customers/withdraw' => 'customers#withdraw'
   resources :customers,only: [:show,:edit,:update]do
    get :favorites, on: :collection
    resources :relationships, only: [:create, :destroy]
   end
   get '/works/ranking/:ranking_name' => 'works#ranking', as: 'works_ranking'
   resources :works, only: [:index,:show,:create,:new,:edit,:update,:destroy]do
    resources :reviews,only: [:index,:show,:new,:create,:destroy]do
     resources :comments,only: [:create,:destroy]
   end
    resources :favorites, only: [:create, :destroy]
   end
   resources :rooms,only: [:index]

   get 'chat/:id' => 'chats#show', as: 'chat'
   delete 'chat/:id' => 'chats#destroy'
   resources :chats, only: [:create]

 end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :customer
  belongs_to :room

  validates :message, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :customer
    belongs_to :review
    belongs_to :parent,  class_name: "Comment", optional: true
    has_many   :replies, class_name: "Comment", foreign_key: :parent_id, dependent: :destroy
    validates :comment, presence: true, length: { in: 1..1000 }
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  enum gender:{
    man:     0, #男
    woman:   1, #女
  }

  attachment :image

  validates :nicname, presence: true
  validates :introduction, presence: true
  validates :email, presence: true


  def self.looks(search, word)
    if search == "perfect_match"
      @customer = Customer.where("nicname LIKE?", "#{word}")
    elsif search == "forward_match"
      @customer = Customer.where("nicname LIKE?","#{word}%")
    elsif search == "backward_match"
      @customer = Customer.where("nicname LIKE?","%#{word}")
    elsif search == "partial_match"
      @customer = Customer.where("nicname LIKE?","%#{word}%")
    else
      @customer = Customer.all
    end
  end

  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following_customer, through: :follower, source: :followed
  has_many :follower_customer, through: :followed, source: :follower


  def follow(cusromer_id)
    follower.create(followed_id: cusromer_id)
  end


  def unfollow(customer_id)
    follower.find_by(followed_id: customer_id).destroy
  end


  def following?(customer)
    following_customer.include?(customer)
  end

  has_many :reviews, dependent: :destroy
  has_many :matchings, dependent: :destroy
  has_many :chats, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :works, dependent: :destroy
  has_many :comments, dependent: :destroy

end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :customer
    belongs_to :work
    
    validates_uniqueness_of :work_id, scope: :customer_id 
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :works, dependent: :destroy
    
    validates :name, presence: true
end

app/models/matching.rb
class Matching < ApplicationRecord
    belongs_to :customer
    belongs_to :room
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "Customer"
  belongs_to :followed, class_name: "Customer"
end

app/models/review.rb
class Review < ApplicationRecord
     belongs_to :customer
     belongs_to :work
     has_many :comments, dependent: :destroy
     
     validates :rate, numericality: {
          less_than_or_equal_to: 5,
          greater_than_or_equal_to: 1
     }, presence: true
     
     validates :thoughts, presence: true
     
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :matchings
  has_many :chats
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tagmaps, dependent: :destroy
  has_many :blogs, through: :tagmaps

  validates :name, presence: true
end

app/models/tagmap.rb
class Tagmap < ApplicationRecord
  belongs_to :work
  belongs_to :tag
end

app/models/work.rb
class Work < ApplicationRecord
    has_many :tagmaps, dependent: :destroy
    has_many :tags, through: :tagmaps
    belongs_to :genre
    belongs_to :customer
    has_many :reviews, dependent: :destroy
    has_many :favorites, dependent: :destroy

    attachment :image

    accepts_nested_attributes_for :tags, allow_destroy: true

    validates :name, presence: true

    def self.looks(search, word)
        if search == "perfect_match"
          @work = Work.where("name LIKE?", "#{word}")
        elsif search == "forward_match"
          @work = Work.where("name LIKE?","#{word}%")
        elsif search == "backward_match"
          @work = Work.where("name LIKE?","%#{word}")
        elsif search == "partial_match"
          @work = Work.where("name LIKE?","%#{word}%")
        else
          @work = Work.all
        end
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?




  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nicname,:email,:image,:prefectures,:gender,:introduction])
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
    before_action :authenticate_customer!

  def search
    @range = params[:range]
    if @range == "作品"
        @works = Work.looks(params[:search], params[:word])
    else
        @customers = Customer.looks(params[:search], params[:word])
    end
  end
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/admin/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>アニッチング</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <body>
    <header>
      <% if customer_signed_in? %>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
           <a class="navbar-brand" href="/"><span><%= link_to "アニッチング", root_path %></span></a>
           <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
             <span class="navbar-toggler-icon"></span>
           </button>
              <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav ml-auto">
                   <li><%= link_to "マイページ", customers_my_page_path, class:"fas fa-users nav-link text-white"%></li>
                   <li><%= link_to "作品一覧", works_path, class:"fas fa-link nav-link text-white"%></li>
                   <li><%= link_to "フォロー/フォロワー", follow_path, class:"fas fa-users nav-link text-white"%></li>
                   <li><%= link_to "ルーム", rooms_path, class:"fas fa-link nav-link text-white"%></li>
                   <li><%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class:"fas fa-sign-out-alt nav-link text-white"%></li>
                </ul>
              </div>
       </div>
        <%= render 'searches/searches' %>
     </nav>
     <% elsif admin_signed_in? %>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
           <a class="navbar-brand" href="/"><span><%= link_to "アニッチング", admin_path %></span></a>
           <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
             <span class="navbar-toggler-icon"></span>
           </button>
              <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav ml-auto">
                   <li><%= link_to "作品一覧", admin_works_path, class:"fas fa-link nav-link text-white"%></li>
                   <li><%= link_to "会員一覧", admin_customers_path, class:"fas fa-users nav-link text-white"%></li>
                   <li><%= link_to "ジャンル", admin_genres_path, class:"fas fa-link nav-link text-white"%></li>
                   <li><%= link_to "タグ", admin_tags_path, class:"fas fa-link nav-link text-white"%></li>
                   <li><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class:"fas fa-sign-out-alt nav-link text-white"%></li>
                </ul>
              </div>
       </div>
       <%= render 'searches/searches' %>
     </nav>
     <% else %>
     <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
           <a class="navbar-brand" href="/"><span><%= link_to "アニッチング", root_path %></span></a>
           <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
             <span class="navbar-toggler-icon"></span>
           </button>
              <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav ml-auto">
                   <li><%= link_to "About", about_path, class:"fas fa-link nav-link text-white"%></li>
                   <li><%= link_to "作品一覧", works_path, class:"fas fa-link nav-link text-white"%></li>
                   <li><%= link_to "新規登録", new_customer_registration_path, class:"fas fa-user-plus nav-link text-white"%></li>
                   <li><%= link_to "ログイン", new_customer_session_path, class:"fas fa-sign-in-alt nav-link text-white"%></li>
                </ul>
              </div>
       </div>
     </nav>
     <% end %>
   </header>

   <%= yield %>
  <footer>
    <div class="container mt-5">
      <div class="row">
        <div class="mx-auto">
          	<p></p>
      	</div>
      </div>
    </div>
  </footer>
</body>
</html>